import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const JetBrainsMono = localFont({
  src: "./fonts/JetBrainsMono.ttf",
  variable: "--font-jetbrainsmono",
  weight: "100 900",
});

const DecimaPro = localFont({
  src: "./fonts/DecimaPro.ttf",
  variable: "--font-decimapro",
  weight: "100 900",
});

const PaniPuri = localFont({
  src: "./fonts/Panipuri.otf",
  variable: "--font-panipuri",
  weight: "100 900",
});

const Neutro = localFont({
  src: "./fonts/Neutro.otf",
  variable: "--font-neutro",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-neutral-950" lang="en">
      <body
        className={`${DecimaPro.variable} ${JetBrainsMono.variable} ${PaniPuri.variable} ${Neutro.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
